version: 2

models:
  - name: deduped
    columns:
      - name: gender
        tests:
          - accepted_values:
              values: ["f", "m", NULL]
      - name: cohort
        tests:
          - accepted_values:
              values: [202002, 202003, 202004, 202005, 202006]
              quote: false
      - name: vertical
        tests:
          - accepted_values:
              values:
                [
                  "Finance",
                  "Food and Beverage",
                  "Loyalty and Samples",
                  "Media and Entertainment",
                  "Retail",
                  "Sports and Fitness",
                  "Ticketing",
                  "Travel",
                ]
